title: Short-term rental
description: Bem-vindo ao repositório de estudos e conteúdos sobre short-term rental, locação por temporada e algoritmo das plataformas.
theme: minima

markdown: kramdown

plugins:
  - jekyll-feed
